class PostsController < ApplicationController

  #don't need 'index' view method since all posts will be displayed with respect to a topic, on the topic 'show' view

  # find the post that corresponds to the id in the params that was passed to show and assign it to @post
  def show
    @post = Post.find(params[:id])
  end

  # When new is invoked, a new and unsaved Post object is created
  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  # When create is invoked by clicking 'Save', the newly created object is persisted to the database.
  def create
    # we call Post.new to create a new instance of Post.
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])

    # assign a topic to a post
    @post.topic = @topic

    # if we successfully save Post to the database
    if @post.save

      flash[:notice] = "Post was saved."
      # redirect the user to the route generated by @post, the 'show' view
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end


  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end
end
